export const CUSTOM_CODE = {
  wrong_pass: 'Wrong password',
  wrong_cur_pass: "Can't change your password",
  pass_diff: "Can't change your password",
  blocking: 'Sorry',
  blocked: "Can't login",
  permission: 'Permission denied',
  please_login: 'Permission denied',
  expired_token: 'Invalid token',
  invalid_token: 'Invalid token',
  encode_err: 'Encode error',
  mail_server_err: 'Mail server error',
  user_not_found: 'Error',
  username_not_match_email: 'Invalid input',
  registed_before: 'Error when register',
  user_exists: 'Error',
  not_registerd: 'Sorry',
  must_confirm: 'Sorry',
  not_pending: 'Sorry',
  can_not_upload: 'Sorry',
};
